http:
  routers:
    echo:
      rule: "Path(`/echo`)"
      entryPoints:
        - web
      service: echo-svc

    cookie:
      rule: "Path(`/cookie`)"
      entryPoints:
        - web
      service: echo-svc

    catchall:
      rule: "PathPrefix(`/`)"
      entryPoints:
        - web
      middlewares:
        - static-ok
      service: noop@internal

  services:
    echo-svc:
      loadBalancer:
        servers:
          - url: "http://127.0.0.1:9090"

  middlewares:
    static-ok:
      plugin:
        staticresponse:
          statusCode: 200
          body: "OK"
